install.packages("httr")
install.packages("jsonlite")
install.packages("ggplot2")
install.packages('RJSplot')
install.packages('dplyr')
#install.packages('plotly')
install.packages('lubridate')
install.packages('forcats')
